# sample hyprlock.conf
# for more configuration options, refer https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock
#
# rendered text in all widgets supports pango markup (e.g. <b> or <i> tags)
# ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#general-remarks
#
# shortcuts to clear password buffer: ESC, Ctrl+U, Ctrl+Backspace
#
# you can get started by copying this config to ~/.config/hypr/hyprlock.conf
#

$font = Hobbiton Brushhand

general {
    hide_cursor = false
}

# uncomment to enable fingerprint authentication
# auth {
#     fingerprint {
#         enabled = true
#         ready_message = Scan fingerprint to unlock
#         present_message = Scanning...
#         retry_delay = 250 # in milliseconds
#     }
# }

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = ~/wallpapers/ultrawide/middle-earth.png
    blur_passes = 0
}

input-field {
    monitor =
    size = 20%, 10%
    outline_thickness = 0
    inner_color = rgba(0, 0, 0, 0.0) # no fill
    check_color = rgba(0, 0, 0, 0.0) # no fill
    fail_color = rgba(0, 0, 0, 0.0) # no fill

    font_color = rgb(3A2626)
    fade_on_empty = false
    rounding = 15

    font_family = $font
    font_size = 22
    placeholder_text = Speak friend and enter.
    fail_text = You cannot pass!

    # uncomment to use a letter instead of a dot to indicate the typed password
    dots_text_format = o
    # dots_size = 0.4
    dots_spacing = 0.3

    # uncomment to use an input indicator that does not show the password length (similar to swaylock's input indicator)
    # hide_input = true

    position = 210, -720
    halign = left
    valign = top
}

# TIME
label {
    monitor =
    text = $TIME # ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#variable-substitution
    font_size = 90
    color = rgb(3A2626)
    font_family = $font

    position = 450, -330
    halign = left
    valign = top
}

# DATE
label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y" # update every 60 seconds
    font_size = 25
    font_family = $font
    color = rgb(3A2626)

    position = 410, -520
    halign = left
    valign = top
}
