# Application bindings
$terminal = uwsm-app -- xdg-terminal-exec
$browser = omarchy-launch-browser


# Modifier Keys
$hyper = SUPER CTRL ALT SHIFT

unbind = SUPER, T
bindd = SUPER, T, Terminal, exec, $terminal --working-directory="$(omarchy-cmd-terminal-cwd)"

unbind = SUPER, V
bind = SUPER, V, togglefloating,

unbind = SUPER, F
bind = SUPER, F, fullscreen, 0,
bind = SUPER SHIFT, L, exec, hyprlock

bindd = SUPER, E, File manager, exec, uwsm-app -- nautilus --new-window
bindd = SUPER, A, Browser, exec, $browser
bindd = SUPER SHIFT, A, Browser (private), exec, $browser --private
bindd = SUPER, M, Music, exec, omarchy-launch-or-focus spotify
bindd = SUPER SHIFT, T, Activity, exec, $terminal -e btop
bindd = SUPER, D, Docker, exec, $terminal -e lazydocker
bindd = SUPER SHIFT, G, Signal, exec, omarchy-launch-or-focus signal "uwsm-app -- signal-desktop"
bindd = SUPER SHIFT, SLASH, Passwords, exec, uwsm-app -- 1password

# If your web app url contains #, type it as ## to prevent hyprland treating it as a comment
bindd = SUPER SHIFT, C, Calendar, exec, omarchy-launch-webapp "https://www.icloud.com/calendar/"
bindd = SUPER SHIFT, E, Email, exec, omarchy-launch-webapp "https://mail.proton.me/u/0/inbox"
bindd = SUPER, G, WhatsApp, exec, omarchy-launch-or-focus-webapp WhatsApp "https://web.whatsapp.com/"
bindd = SUPER SHIFT, K, Slack, exec, uwsm-app -- slack

unbind = SUPER, O
bindd = SUPER, O, Obsidian, exec, omarchy-launch-or-focus obsidian

# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# unbind = SUPER, SPACE
# bindd = SUPER, SPACE, Omarchy menu, exec, omarchy-menu
