# Application bindings
$terminal = uwsm-app -- xdg-terminal-exec
$browser = omarchy-launch-browser


# Modifier Keys
$hyper = SUPER CTRL ALT SHIFT

# Vim-style window navigation
unbind = SUPER, H
unbind = SUPER, J
unbind = SUPER, K
unbind = SUPER, L
unbind = SUPER SHIFT, H
unbind = SUPER SHIFT, J
unbind = SUPER SHIFT, K
unbind = SUPER SHIFT, L

bindd = SUPER, H, Focus left window, movefocus, l
bindd = SUPER, J, Focus below window, movefocus, d
bindd = SUPER, K, Focus above window, movefocus, u
bindd = SUPER, L, Focus right window, movefocus, r

bindd = SUPER SHIFT, H, Swap window to the left, swapwindow, l
bindd = SUPER SHIFT, J, Swap window down, swapwindow, d
bindd = SUPER SHIFT, K, Swap window up, swapwindow, u
bindd = SUPER SHIFT, L, Swap window to the right, swapwindow, r

unbind = SUPER SHIFT, ESCAPE
bindd = SUPER SHIFT, ESCAPE, Lock screen, exec, omarchy-system-lock

unbind = SUPER, T
bindd = SUPER, T, Terminal, exec, $terminal --working-directory="$(omarchy-cmd-terminal-cwd)"

unbind = SUPER, V
bind = SUPER, V, togglefloating,

unbind = SUPER, F
bind = SUPER, F, fullscreen, 0,

bindd = SUPER, E, File manager, exec, uwsm-app -- nautilus --new-window
bindd = SUPER, A, Browser, exec, $browser
bindd = SUPER SHIFT, A, Browser (private), exec, $browser --private
bindd = SUPER, M, Music, exec, omarchy-launch-or-focus spotify
bindd = SUPER SHIFT, T, Activity, exec, $terminal -e btop
bindd = SUPER, D, Docker, exec, $terminal -e lazydocker
bindd = SUPER SHIFT, G, Signal, exec, omarchy-launch-or-focus signal "uwsm-app -- signal-desktop"
unbind = SUPER SHIFT, S
bindd = SUPER SHIFT, S, Slack, exec, uwsm-app -- slack
bindd = SUPER SHIFT, SLASH, Passwords, exec, uwsm-app -- 1password

# If your web app url contains #, type it as ## to prevent hyprland treating it as a comment
bindd = SUPER SHIFT, C, Calendar, exec, omarchy-launch-webapp "https://www.icloud.com/calendar/"
bindd = SUPER SHIFT, E, Email, exec, omarchy-launch-webapp "https://mail.proton.me/u/0/inbox"
bindd = SUPER, G, WhatsApp, exec, omarchy-launch-or-focus-webapp WhatsApp "https://web.whatsapp.com/"

unbind = SUPER, O
bindd = SUPER, O, Obsidian, exec, omarchy-launch-or-focus obsidian

# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# unbind = SUPER, SPACE
# bindd = SUPER, SPACE, Omarchy menu, exec, omarchy-menu
